name: DeployForge CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint application
        run: |
          pip install ruff
          ruff check app/

      - name: Security scan
        run: |
          pip install pip-audit
          pip-audit

      - name: Build Docker image
        run: |
          docker build -t deployforge:${{ github.sha }} .

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::478982786478:role/deployforge-github-actions
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        if: github.event_name == 'push'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: deployforge
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker tag deployforge:${IMAGE_TAG} ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}

      - name: Push Docker image to ECR
        if: github.event_name == 'push'
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: deployforge
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}


  deploy:
    name: Deploy to EC2
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Logging in to Amazon ECR..."
            aws ecr get-login-password --region ap-south-1 | \
              docker login --username AWS --password-stdin \
              478982786478.dkr.ecr.ap-south-1.amazonaws.com

            echo "Pulling new DeployForge image..."
            docker pull \
              478982786478.dkr.ecr.ap-south-1.amazonaws.com/deployforge:${{ github.sha }}

            echo "Stopping old container..."
            docker stop deployforge-api || true

            echo "Removing old container..."
            docker rm deployforge-api || true

            echo "Starting new container..."
            docker run -d \
              --name deployforge-api \
              -p 8000:8000 \
              --restart unless-stopped \
              478982786478.dkr.ecr.ap-south-1.amazonaws.com/deployforge:${{ github.sha }}

            echo "Waiting for application..."
            sleep 5

            echo "Checking application health..."
            curl --fail http://localhost:8000/health

            echo "Deployment successful!"